name: rlkit-gpu
channels:
- kne  # for pybox2d
- pytorch
- anaconda  # for mkl
dependencies:
- pyyaml
- joblib=0.9.4
- mako=1.0.6=py35_0
- matplotlib=2.0.2=np111py35_0
- mkl=2018.0.2  # Need to add explicit dependence for pytorch
- numba=0.35.0=np111py35_0
- numpy=1.11.3
- path.py=10.3.1=py35_0
- python=3.5.2
- python-dateutil=2.6.1=py35_0
- pip:
  - http://download.pytorch.org/whl/cu90/torch-0.3.1-cp35-cp35m-linux_x86_64.whl
- scipy=1.0.1
- patchelf
- pip:
  - cloudpickle==0.5.2
  - gym[mujoco]==0.10.5
  - gitpython==2.1.7
  - gtimer==1.0.0b5
